### ISSUE TITLE
Todo - 정민

### ISSUE THREAD

**Issue by jmini1234** [jmini1234/centras_web#15]
[Back]
- [x]  카메라 ip 등록하는 back-end 추가 
- [x]  사용자가 버튼 누르면 양식장 크기 분류 update

[ESP]
- [x] esp 연동 데이터 저장 code 작성

[추후]
- [ ]  백엔드 코드 리팩토링

**Comment by jmini1234** [comment]
최근 row 만 update 하는 query 추가 구현 필요
